#:schema node_modules/wrangler/config-schema.json
name = "insight-weaver-api"
main = "src/index.ts"
compatibility_date = "2024-09-04"
compatibility_flags = ["nodejs_compat"]

# Variables
[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "insight-weaver-db"
database_id = "your-database-id-here"
migrations_dir = "schema"

# Vectorize binding for semantic search
[[vectorize]]
binding = "VECTORIZE"
index_name = "insight-weaver-embeddings"

# AI binding
[ai]
binding = "AI"

# KV binding for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Scheduled triggers for RSS fetching
[[triggers]]
crons = ["0 */30 * * * *"]  # Every 30 minutes